project_id = "pqptgpntbthrisnuwwzi"

[functions.seed-platform-admin]
verify_jwt = false

[functions.process-lead-assignments]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.sync-emails]
verify_jwt = true